version: "2"

services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
    ports:
      - 5432:5432
    working_dir: /app
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

  node:
    image: "node:18"
    working_dir: /app
    volumes:
      - ./backend/:/app
    ports:
      - "8080:8080"
    command: "npm run dev"